<h2 style="font-weight: bold;">ANALYSIS OF A LOANS DATASET</h2>
<p>This is an analysis of the loan_train.csv file to derive insight from the data</p>
<p>Our group used questions to help us analyze the data and understand the story of the dataset. They questions are as follows:</p>
<ol>
    <li>What factors most significantly influence whether a loan is approved or not?</li>
    <li>What is the relationship between marital status and loan approval?</li>
    <li>What are the most common loan terms(in months) and they affect approval rates?</li>
    <li>Is there a correlation between the applicant's income and the loan amount?</li>
    <li>Do applicants from urban areas have higher loan approval rates compared to those from rural or semi-urban areas?</li>
    <li>What is the effect of the number of dependents on loan approval?</li>
    <li>What is the distribution of loan approvals across different property areas?</li>
    <li>How does the applicant's education level affect loan approval rates?</li>
    <li>How does the applicant's self-employment status affect loan approval chances?</li>
    <li>Are there differences in loan approval rates based on gender?</li>
    <li>How does the presence of a co-applicant affect the likelihood of loan approval?</li>
    <li>Is there a correlation between the combined income of the applicant and co-applicant and the loan amount?</li>
</ol>


In [22]:
#importing packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [23]:
#To call on the dataset
data = pd.read_csv("loan_train.csv")

In [24]:
#disply the first few rows
data.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [25]:
data.tail()

Loan_ID  Gender Married Dependents Education Self_Employed  \
609  LP002978  Female      No          0  Graduate            No   
610  LP002979    Male     Yes         3+  Graduate            No   
611  LP002983    Male     Yes          1  Graduate            No   
612  LP002984    Male     Yes          2  Graduate            No   
613  LP002990  Female      No          0  Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [26]:
#To show the columns in the dataset
data.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [27]:
#to get a statistical summary of the dataset
data.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [28]:
#to get a summary of the data-frame
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [29]:
#To check for missing values
data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [30]:
#changes the column name
data = data.rename(columns={'Loan_Amount_Term': "Loan_Term(months)"})
data.sample(1)                   

Loan_ID  Gender Married Dependents Education Self_Employed  \
495  LP002586  Female     Yes          1  Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Term(months)  \
495             3326              913.0       105.0               84.0   

     Credit_History Property_Area Loan_Status  
495             1.0     Semiurban           Y

In [31]:
#removing missing values from select columns
data_cleaned = data.dropna(subset=['Gender', 'Married'])


In [32]:
data_cleaned.isnull().sum()
#the results will show that the missing values from the Gender and Married columns have been removed

Loan_ID               0
Gender                0
Married               0
Dependents           12
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           21
Loan_Term(months)    14
Credit_History       49
Property_Area         0
Loan_Status           0
dtype: int64

In [33]:
data_cleaned = data_cleaned.drop_duplicates()

In [34]:
data_cleaned.shape
#this shows that 16 duplicate rows have been removed

(598, 13)

In [35]:
#finding the percentage of missing values
data_cleaned.isnull().sum()/data_cleaned.shape[0]*100
#since the columns have low percentages of missing values we are able to remove them without affecting the results of analysis

Loan_ID              0.000000
Gender               0.000000
Married              0.000000
Dependents           2.006689
Education            0.000000
Self_Employed        5.351171
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           3.511706
Loan_Term(months)    2.341137
Credit_History       8.193980
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

In [36]:
#removing the missing values
data_cleaned.dropna(axis=0, inplace=True)

In [37]:
data_cleaned.isnull().sum()
#the missing values have been removed

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Term(months)    0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

<h1 style="font-weight: bold;">DATA CLEANING</h1>
<p>We will go through each column to verify that there are no non-numerical values that can affect data analysis process</p>

In [38]:
#creating a copy of the data
loans = data_cleaned.copy()
#our data copy has been created
loans.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   
5  LP001011   Male     Yes          2      Graduate           Yes   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Term(months)  \
1             4583             1508.0       128.0              360.0   
2             3000                0.0        66.0              360.0   
3             2583             2358.0       120.0              360.0   
4             6000                0.0       141.0              360.0   
5             5417             4196.0       267.0              360.0   

   Credit_History Property_Area Loan_Status  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y

In [39]:
loans.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Term(months)    0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [40]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
Index: 480 entries, 1 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            480 non-null    object 
 1   Gender             480 non-null    object 
 2   Married            480 non-null    object 
 3   Dependents         480 non-null    object 
 4   Education          480 non-null    object 
 5   Self_Employed      480 non-null    object 
 6   ApplicantIncome    480 non-null    int64  
 7   CoapplicantIncome  480 non-null    float64
 8   LoanAmount         480 non-null    float64
 9   Loan_Term(months)  480 non-null    float64
 10  Credit_History     480 non-null    float64
 11  Property_Area      480 non-null    object 
 12  Loan_Status        480 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 52.5+ KB


In [41]:
#has dropped the Loan_ID column
loans = loans.drop(columns = "Loan_ID")

In [42]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
Index: 480 entries, 1 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             480 non-null    object 
 1   Married            480 non-null    object 
 2   Dependents         480 non-null    object 
 3   Education          480 non-null    object 
 4   Self_Employed      480 non-null    object 
 5   ApplicantIncome    480 non-null    int64  
 6   CoapplicantIncome  480 non-null    float64
 7   LoanAmount         480 non-null    float64
 8   Loan_Term(months)  480 non-null    float64
 9   Credit_History     480 non-null    float64
 10  Property_Area      480 non-null    object 
 11  Loan_Status        480 non-null    object 
dtypes: float64(4), int64(1), object(7)
memory usage: 48.8+ KB


In [43]:
loans

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
1      Male     Yes          1      Graduate            No             4583   
2      Male     Yes          0      Graduate           Yes             3000   
3      Male     Yes          0  Not Graduate            No             2583   
4      Male      No          0      Graduate            No             6000   
5      Male     Yes          2      Graduate           Yes             5417   
..      ...     ...        ...           ...           ...              ...   
609  Female      No          0      Graduate            No             2900   
610    Male     Yes         3+      Graduate            No             4106   
611    Male     Yes          1      Graduate            No             8072   
612    Male     Yes          2      Graduate            No             7583   
613  Female      No          0      Graduate           Yes             4583   

     CoapplicantIncome  LoanAmount  Loan_Term(months)  Credit_History  \
1               1508.0       128.0              360.0             1.0   
2                  0.0        66.0              360.0             1.0   
3               2358.0       120.0              360.0             1.0   
4                  0.0       141.0              360.0             1.0   
5               4196.0       267.0              360.0             1.0   
..                 ...         ...                ...             ...   
609                0.0        71.0              360.0             1.0   
610                0.0        40.0              180.0             1.0   
611              240.0       253.0              360.0             1.0   
612                0.0       187.0              360.0             1.0   
613                0.0       133.0              360.0             0.0   

    Property_Area Loan_Status  
1           Rural           N  
2           Urban           Y  
3           Urban           Y  
4           Urban           Y  
5           Urban           Y  
..            ...         ...  
609         Rural           Y  
610         Rural           Y  
611         Urban           Y  
612         Urban           Y  
613     Semiurban           N  

[480 rows x 12 columns]

In [44]:
loans.tail()

Gender Married Dependents Education Self_Employed  ApplicantIncome  \
609  Female      No          0  Graduate            No             2900   
610    Male     Yes         3+  Graduate            No             4106   
611    Male     Yes          1  Graduate            No             8072   
612    Male     Yes          2  Graduate            No             7583   
613  Female      No          0  Graduate           Yes             4583   

     CoapplicantIncome  LoanAmount  Loan_Term(months)  Credit_History  \
609                0.0        71.0              360.0             1.0   
610                0.0        40.0              180.0             1.0   
611              240.0       253.0              360.0             1.0   
612                0.0       187.0              360.0             1.0   
613                0.0       133.0              360.0             0.0   

    Property_Area Loan_Status  
609         Rural           Y  
610         Rural           Y  
611         Urban           Y  
612         Urban           Y  
613     Semiurban           N

<h1>Checking values</h1>
<p>In this section, we checked whether the values we checked for unique values and the data types in the data set</p>

<ol style= "font-weight: bold;">
    <h3>1. Gender</h3>
</ol>
<p>Missing values were omitted</p>


In [50]:
loans['Gender'].unique()

array(['Male', 'Female'], dtype=object)

<ol style= "font-weight: bold;">
    <h3>2. Married</h3>
</ol>
<p>Missing values were omitted</p>


In [51]:
loans['Married'].unique()

array(['Yes', 'No'], dtype=object)

<ol style= "font-weight: bold;">
    <h3>3. Dependents</h3>
</ol>


In [52]:
# Function to strip non-numeric characters which in this case is the plus sign after 3
def strip_non_numbers(value):
     # Use regular expression to replace non-numeric characters with an empty string
     #calls on the imported library
     return re.sub(r'\D', '', str(value))

 # Apply the function to the specific column
loans['Dependents'] = loans['Dependents'].apply(strip_non_numbers)

In [53]:
loans.tail()
#results below show that the '+' has been removed

Gender Married Dependents Education Self_Employed  ApplicantIncome  \
609  Female      No          0  Graduate            No             2900   
610    Male     Yes          3  Graduate            No             4106   
611    Male     Yes          1  Graduate            No             8072   
612    Male     Yes          2  Graduate            No             7583   
613  Female      No          0  Graduate           Yes             4583   

     CoapplicantIncome  LoanAmount  Loan_Term(months)  Credit_History  \
609                0.0        71.0              360.0             1.0   
610                0.0        40.0              180.0             1.0   
611              240.0       253.0              360.0             1.0   
612                0.0       187.0              360.0             1.0   
613                0.0       133.0              360.0             0.0   

    Property_Area Loan_Status  
609         Rural           Y  
610         Rural           Y  
611         Urban           Y  
612         Urban           Y  
613     Semiurban           N

<ol style= "font-weight: bold;">
    <h3>4. Education</h3>
</ol>


In [54]:
loans['Education'].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

<ol style= "font-weight: bold;">
    <h3>5. Self_Employed</h3>
</ol>


In [49]:
loans['Self_Employed'].unique()

array(['No', 'Yes'], dtype=object)

<ol style= "font-weight: bold;">
    <h3>6. Applicant Income</h3>
</ol>

In [57]:
loans['ApplicantIncome'].unique()

array([ 4583,  3000,  2583,  6000,  5417,  2333,  3036,  4006, 12841,
        3200,  3073,  1853,  1299,  4950,  3510,  4887,  7660,  5955,
        2600,  9560,  2799,  4226,  1442,  3167,  4692,  3500, 12500,
        3667,  4166,  3748,  3600,  1800,  3941,  5649,  5821,  2645,
        4000,  1928,  3086,  4230,  4616, 11500,  2708,  2132,  3366,
        8080,  3357,  2500,  3029,  2609,  5726, 10750,  7100,  4300,
        3208,  1875,  5266,  3750,  1000,  3846,  1378,  3988,  2366,
        8566,  5695,  2958,  6250,  3273,  4133,  3620,  2484,  1977,
        4188,  1759,  4288,  4843,  3052, 11417,  3800,  2071,  5316,
       14583,  5568, 10408,  2137,  2957, 10513,  2014,  2718,  3459,
        4895,  3316, 14999,  4200,  5042,  6950,  2698, 11757,  2330,
       14866,  1538, 10000,  4860,  6277,  2577,  9166,  2281,  3254,
       39999,  9538,  1863,  7933,  3089,  4167,  9323,  2439,  2237,
        8000,  3522,  5708,  4344,  3497,  2045,  5516,  6400,  4600,
       33846,  3625,

<ol style= "font-weight: bold;">
    <h3>7. Coapplicant Income</h3>
</ol>

In [58]:
loans['CoapplicantIncome'].unique()

array([1.50800000e+03, 0.00000000e+00, 2.35800000e+03, 4.19600000e+03,
       1.51600000e+03, 2.50400000e+03, 1.52600000e+03, 1.09680000e+04,
       7.00000000e+02, 8.10600000e+03, 2.84000000e+03, 1.08600000e+03,
       5.62500000e+03, 1.91100000e+03, 2.25300000e+03, 1.04000000e+03,
       1.66700000e+03, 3.00000000e+03, 1.45900000e+03, 7.21000000e+03,
       1.66800000e+03, 1.21300000e+03, 2.33600000e+03, 3.44000000e+03,
       2.27500000e+03, 1.64400000e+03, 1.16700000e+03, 1.59100000e+03,
       2.20000000e+03, 2.25000000e+03, 2.85900000e+03, 3.79600000e+03,
       3.44900000e+03, 4.59500000e+03, 2.25400000e+03, 3.06600000e+03,
       1.87500000e+03, 1.77400000e+03, 4.75000000e+03, 3.02200000e+03,
       4.00000000e+03, 1.88100000e+03, 2.53100000e+03, 2.11800000e+03,
       4.16700000e+03, 2.90000000e+03, 5.65400000e+03, 1.82000000e+03,
       2.30200000e+03, 9.97000000e+02, 3.54100000e+03, 3.26300000e+03,
       3.80600000e+03, 1.03000000e+03, 1.12600000e+03, 3.60000000e+03,
      

In [ ]:
#another column of their total income

<ol style= "font-weight: bold;">
    <h3>8. Loan Amount</h3>
</ol>

In [59]:
loans['LoanAmount'].unique()

array([128.,  66., 120., 141., 267.,  95., 158., 168., 349.,  70., 200.,
       114.,  17., 125.,  76., 133., 104., 315., 116., 191., 122., 110.,
        35.,  74., 106., 320., 144., 184.,  80.,  47., 134.,  44., 100.,
       112., 286.,  97.,  96., 135., 180.,  99., 165., 258., 126., 312.,
       136., 172.,  81., 187., 113., 176., 111., 167.,  50., 210., 175.,
       131., 188.,  25., 137., 115., 151., 225., 216.,  94., 185., 154.,
       259., 194., 160., 102., 290.,  84.,  88., 242., 129.,  30., 118.,
       152., 244., 600., 255.,  98., 275., 121.,  75.,  63.,  87., 101.,
       495.,  73., 260., 108.,  48., 164., 170.,  83.,  90., 166., 124.,
        55.,  59., 127., 214., 240., 130.,  60., 280., 140., 155., 123.,
       201., 138., 279., 192., 304., 150., 207., 436.,  78.,  54.,  89.,
       139.,  93., 132., 480.,  56., 300., 376.,  67., 117.,  71., 173.,
        46., 228., 308., 105., 236., 570., 380., 296., 156., 109., 103.,
        45.,  65.,  53., 360.,  62., 218., 178., 23

<ol style= "font-weight: bold;">
    <h3>9. Loan_Term(months)</h3>
</ol>

In [60]:
loans['Loan_Term(months)'].unique()

array([360., 120., 180.,  60., 300., 480., 240.,  36.,  84.])

<ol style= "font-weight: bold;">
    <h3>10. Credit History</h3>
</ol>

In [61]:
loans['Credit_History'].unique()

array([1., 0.])

<ol style= "font-weight: bold;">
    <h3>11. Property Area</h3>
</ol>

In [62]:
loans['Property_Area'].unique()

array(['Rural', 'Urban', 'Semiurban'], dtype=object)

<ol style= "font-weight: bold;">
    <h3>12. Loan Status</h3>
</ol>

In [63]:
loans['Loan_Status'].unique()

array(['N', 'Y'], dtype=object)

<h1 style="font-weight: bold">DATA EXPLORATION AND ANALYSIS</h1>

<ul style="list-style-type: none;">
    <li style="font-size: 20px; font-weight: bold;">
        1. What factors most significantly influence whether a loan is approved or not?
    </li>
</ul>

<ul style="list-style-type: none;">
    <li style="font-size: 20px; font-weight: bold;">
        2. What is the relationship between marital status and loan approval?
    </li>
</ul>

<ul style="list-style-type: none;">
    <li style="font-size: 20px; font-weight: bold;">
        3. What is the relationship between marital status and loan approval?
    </li>
</ul>

<ul style="list-style-type: none;">
    <li style="font-size: 20px; font-weight: bold;">
        4. What is the relationship between marital status and loan approval?
    </li>
</ul>

<ul style="list-style-type: none;">
    <li style="font-size: 20px; font-weight: bold;">
        5. What is the relationship between marital status and loan approval?
    </li>
</ul>

<ul style="list-style-type: none;">
    <li style="font-size: 20px; font-weight: bold;">
        6. What is the relationship between marital status and loan approval?
    </li>
</ul>

<ul style="list-style-type: none;">
    <li style="font-size: 20px; font-weight: bold;">
        7. What is the relationship between marital status and loan approval?
    </li>
</ul>

<ul style="list-style-type: none;">
    <li style="font-size: 20px; font-weight: bold;">
        8. What is the relationship between marital status and loan approval?
    </li>
</ul>

<ul style="list-style-type: none;">
    <li style="font-size: 20px; font-weight: bold;">
        9. What is the relationship between marital status and loan approval?
    </li>
</ul>